assets/scss/components/_horizontal-search-form.scss, server/routes/manage-key-workers/view.njk
=> MIA-252: Update key worker name field width

server/routes/manage-key-workers/tests.cy.ts, server/routes/manage-key-workers/view.njk
=> MIA-368: Add empty (none) status filter option

integration_tests/mockApis/keyworkerApi.ts, server/middleware/validationMiddleware.ts, server/routes/allocate-key-workers/controller.ts, server/routes/allocate-key-workers/tests.cy.ts, server/routes/allocate-key-workers/view.njk, server/routes/manage-key-workers/controller.ts, server/routes/manage-key-workers/tests.cy.ts, server/routes/prisoner-allocation-history/controller.ts, server/routes/prisoner-allocation-history/tests.cy.ts
=> MIA-369: Persisting search params on prisoner-allocation-history back link

integration_tests/index.d.ts, integration_tests/mockApis/keyworkerApi.ts, integration_tests/support/commands.ts, server/@types/express/index.d.ts, server/routes/journeys/update-capacity-status/cancel/controller.ts, server/routes/journeys/update-capacity-status/cancel/routes.ts, server/routes/journeys/update-capacity-status/cancel/tests.cy.ts, server/routes/journeys/update-capacity-status/common/utils.ts, server/routes/journeys/update-capacity-status/controller.ts, server/routes/journeys/update-capacity-status/routes.ts, server/routes/journeys/update-capacity-status/schema.ts, server/routes/journeys/update-capacity-status/tests.cy.ts, server/routes/journeys/update-capacity-status/update-status-inactive/controller.ts, server/routes/journeys/update-capacity-status/update-status-inactive/routes.ts, server/routes/journeys/update-capacity-status/update-status-inactive/tests.cy.ts, server/routes/journeys/update-capacity-status/update-status-inactive/view.njk, server/routes/journeys/update-capacity-status/view.njk, server/routes/key-worker-statistics/controller.ts, server/services/keyworkerApi/keyworkerApiClient.ts, server/services/keyworkerApi/keyworkerApiService.ts, server/utils/constants.ts
=> MIA-256 update-status-inactive page

server/routes/journeys/update-capacity-status/cancel/controller.ts, server/routes/journeys/update-capacity-status/check-answers/controller.ts, server/routes/journeys/update-capacity-status/check-answers/routes.ts, server/routes/journeys/update-capacity-status/check-answers/tests.cy.ts, server/routes/journeys/update-capacity-status/check-answers/view.njk, server/routes/journeys/update-capacity-status/common/utils.ts, server/routes/journeys/update-capacity-status/controller.ts, server/routes/journeys/update-capacity-status/routes.ts, server/routes/journeys/update-capacity-status/update-status-unavailable/controller.ts, server/routes/journeys/update-capacity-status/update-status-unavailable/routes.ts, server/routes/journeys/update-capacity-status/update-status-unavailable/schema.ts, server/routes/journeys/update-capacity-status/update-status-unavailable/tests.cy.ts, server/routes/journeys/update-capacity-status/update-status-unavailable/view.njk
=> MIA-256 update-status-unavailable and check-answers pages

server/routes/allocate-key-workers/tests.cy.ts, server/routes/allocate-key-workers/view.njk, server/utils/nunjucksSetup.ts
=> MIA-390: Read only allocate key workers view

integration_tests/mockApis/keyworkerApi.ts, server/@types/express/index.d.ts, server/@types/keyWorker/index.d.ts, server/routes/establishment-settings/controller.ts, server/routes/establishment-settings/routes.ts, server/routes/establishment-settings/schema.ts, server/routes/establishment-settings/tests.cy.ts, server/routes/establishment-settings/view.njk, server/routes/index.ts, server/routes/test.cy.ts, server/routes/view.njk, server/services/keyworkerApi/keyworkerApiClient.ts, server/services/keyworkerApi/keyworkerApiService.ts, server/utils/validation/validateNumber.ts
=> MIA-371 /establishment-settings page

.gitleaks/.gitleaksignore, .gitleaks/config.toml, .husky/pre-commit, package-lock.json, package.json
Adding a fake secret (random base64 enc string)
=> MIA-468: Use HMPPS pre commit hooks in UI

integration_tests/mockApis/keyworkerApi.ts, server/routes/journeys/update-capacity-status/check-answers/controller.ts, server/routes/journeys/update-capacity-status/check-answers/tests.cy.ts, server/routes/journeys/update-capacity-status/controller.ts, server/routes/journeys/update-capacity-status/e2e.cy.ts, server/routes/journeys/update-capacity-status/tests.cy.ts, server/routes/journeys/update-capacity-status/update-status-annual-leave-return/tests.cy.ts, server/routes/journeys/update-capacity-status/update-status-annual-leave-return/view.njk, server/routes/journeys/update-capacity-status/update-status-inactive/controller.ts, server/routes/journeys/update-capacity-status/update-status-inactive/tests.cy.ts, server/routes/journeys/update-capacity-status/update-status-inactive/view.njk, server/routes/journeys/update-capacity-status/update-status-unavailable/tests.cy.ts, server/routes/journeys/update-capacity-status/update-status-unavailable/view.njk, server/services/keyworkerApi/keyworkerApiClient.ts, server/services/keyworkerApi/keyworkerApiService.ts
=> MIA-440 Update key worker status/capacity journey to work for both policies

assets/scss/components/_horizontal-search-form.scss
=> Make checkbox background white on allocate page

assets/scss/local.scss, server/middleware/permissionsMiddleware.ts, server/routes/view.njk
=> Fix css on homepage

server/routes/allocate/tests.cy.ts, server/routes/allocate/view.njk
=> MIA-534 Add staff profile links to allocate staff page

integration_tests/mockApis/keyworkerApi.ts, server/routes/journeys/update-capacity-status/cancel/tests.cy.ts, server/routes/journeys/update-capacity-status/tests.cy.ts, server/routes/staff-profile/tests.cy.ts, server/routes/staff-profile/view.njk, server/testutils/mockObjects.ts
=> MIA-527: Fix "keyworker" static reference on staff profile

integration_tests/mockApis/keyworkerApi.ts, server/@types/keyWorker/index.d.ts, server/routes/journeys/manage-roles/assign/check-answers/controller.ts, server/routes/journeys/manage-roles/assign/check-answers/tests.cy.ts, server/routes/journeys/manage-roles/assign/e2e.cy.ts, server/routes/journeys/manage-roles/remove/e2e.cy.ts, server/routes/journeys/manage-roles/remove/remove-role/controller.ts, server/routes/journeys/manage-roles/remove/remove-role/tests.cy.ts, server/routes/journeys/update-capacity-status/check-answers/controller.ts, server/routes/journeys/update-capacity-status/check-answers/tests.cy.ts, server/routes/journeys/update-capacity-status/controller.ts, server/routes/journeys/update-capacity-status/e2e.cy.ts, server/routes/journeys/update-capacity-status/tests.cy.ts, server/routes/journeys/update-capacity-status/update-status-annual-leave-return/tests.cy.ts, server/routes/journeys/update-capacity-status/update-status-inactive/controller.ts, server/routes/journeys/update-capacity-status/update-status-inactive/tests.cy.ts, server/routes/journeys/update-capacity-status/update-status-unavailable/tests.cy.ts, server/services/keyworkerApi/keyworkerApiClient.ts, server/services/keyworkerApi/keyworkerApiService.ts, server/utils/utils.ts
=> MIA-517 Unify manage staff role and staff config pages to use the same upsert staff details endpoint

server/@types/express/index.d.ts, server/routes/journeys/manage-roles/assign/capacity/controller.ts, server/routes/journeys/manage-roles/assign/capacity/routes.ts, server/routes/journeys/manage-roles/assign/capacity/schema.ts, server/routes/journeys/manage-roles/assign/capacity/tests.cy.ts, server/routes/journeys/manage-roles/assign/capacity/view.njk, server/routes/journeys/manage-roles/assign/check-answers/controller.ts, server/routes/journeys/manage-roles/assign/check-answers/tests.cy.ts, server/routes/journeys/manage-roles/assign/check-answers/view.njk, server/routes/journeys/manage-roles/assign/confirmation/tests.cy.ts, server/routes/journeys/manage-roles/assign/confirmation/view.njk, server/routes/journeys/manage-roles/assign/controller.ts, server/routes/journeys/manage-roles/assign/e2e.cy.ts, server/routes/journeys/manage-roles/assign/role/view.njk, server/routes/journeys/manage-roles/assign/routes.ts, server/routes/journeys/manage-roles/assign/tests.cy.ts, server/routes/journeys/manage-roles/assign/working-pattern/controller.ts, server/routes/journeys/manage-roles/assign/working-pattern/tests.cy.ts, server/routes/journeys/manage-roles/assign/working-pattern/view.njk, server/routes/journeys/manage-roles/remove/controller.ts, server/routes/journeys/manage-roles/remove/remove-role/tests.cy.ts, server/routes/journeys/manage-roles/remove/remove-role/view.njk, server/routes/journeys/manage-roles/remove/tests.cy.ts, server/routes/recommend-allocations/view.njk, server/routes/test.cy.ts, server/routes/view.njk
=> MIA-548 Update assign/remove key worker role journey

.hardcodecheckignore, assets/scss/components/_horizontal-search-form.scss, server/routes/manage/tests.cy.ts, server/routes/manage/view.njk, server/views/partials/statusTag/macro.njk
=> MIA-454: MVP changes for "Manage" page

server/routes/recommend-allocations/tests.cy.ts, server/routes/recommend-allocations/view.njk
=> MIA-549 Update wordings on recommend allocations page

integration_tests/mockApis/keyworkerApi.ts, server/routes/allocate/controller.ts, server/routes/allocate/routes.ts, server/routes/allocate/view.njk, server/routes/base/changeStaffController.ts, server/routes/recommend-allocations/controller.ts, server/routes/recommend-allocations/not-enough-available-capacity/tests.cy.ts, server/routes/recommend-allocations/not-enough-available-capacity/view.njk, server/routes/recommend-allocations/routes.ts, server/routes/recommend-allocations/tests.cy.ts, server/routes/staff-profile/routes.ts, server/utils/constants.ts
=> Revamp auto allocation journey

helm_deploy/hmpps-allocate-key-workers-ui/values.yaml, server/@types/express/index.d.ts, server/app.ts, server/data/auditedRestClient.ts, server/data/restClient.ts, server/middleware/audit/auditApiCallMiddleware.ts, server/routes/establishment-settings/tests.cy.ts, server/services/keyworkerApi/keyworkerApiClient.ts, server/services/keyworkerApi/keyworkerApiService.ts
=> MIA-405 Add audit events for data modification requests

server/routes/allocate/tests.cy.ts, server/routes/allocate/view.njk
=> Adding auto allocate button back on allocate page load

integration_tests/mockApis/keyworkerApi.ts, server/routes/controller.ts, server/routes/test.cy.ts, server/routes/view.njk
=> MIA-637 Change homepage allocation tile content

integration_tests/mockApis/keyworkerApi.ts, server/routes/allocate/tests.cy.ts, server/routes/base/changeStaffController.ts
Sorting by last name when the allocation numbers are equal
=> MIA-675: Include name in sorting order for key worker dropdown

server/routes/establishment-settings/schema.ts, server/routes/establishment-settings/tests.cy.ts, server/routes/establishment-settings/view.njk
=> MIA-633: Personal officer establishment settings changes

server/routes/staff-profile/components/statCard.njk
=> Fix header level on staff profile page

server/routes/allocate/controller.ts, server/routes/allocate/tests.cy.ts, server/routes/allocate/view.njk, server/routes/recommend-allocations/controller.ts, server/routes/recommend-allocations/tests.cy.ts, server/routes/recommend-allocations/view.njk, server/routes/staff-profile-personal-officer/controller.ts, server/routes/staff-profile-personal-officer/tests.cy.ts, server/routes/staff-profile-personal-officer/view.njk, server/routes/staff-profile/controller.ts, server/routes/staff-profile/tests.cy.ts, server/routes/staff-profile/view.njk, server/utils/utils.ts, server/views/partials/alertFlags/macro.njk
^ Redirects back to prisoner profile on dev because service redirects are environment scoped
=> MIA-730: Using backlink in prisoner profile service
